function T = pqw2ijk(raan, inc, ap)

A = [cosd(-raan), sind(-raan), 0;...
    -sind(-raan), cosd(-raan), 0;...
    0, 0, 1];

B = [1, 0, 0;...
    0, cosd(-inc), sind(-inc);...
    0, -sind(-inc), cosd(-inc)];

C = [cosd(-ap), sind(-ap), 0;...
    -sind(-ap), cosd(-ap), 0;...
    0, 0, 1];

T = A*B*C;

end